version: '3.3'

services:
  mysql8:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: unicauca
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring
  unicauca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unicauca
    ports:
      - '8099:8095'
    env_file:
      - .env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
volumes:
  mysql_data:
networks:
  spring: