version: '3.3'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.mysql  # Usar el Dockerfile personalizado
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: unicauca
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - spring
  unicauca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unicauca
    ports:
      - '8099:8095'
    env_file:
      - .env
    networks:
      - spring
    depends_on:
      - database
    restart: always
volumes:
  mysql_data:
networks:
  spring: